name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install everything that is needed
      run: |
          sudo apt-get update 
          sudo apt-get upgrade
          sudo apt-get install -y xserver-xorg-core xserver-xorg xorg xvfb bspwm 
          sudo apt-get install zathura

    - name: Add config for bspwm and sxhkd
      run: |
        mkdir -p $HOME/.config/bspwm
        mkdir -p $HOME/.config/sxhkd

        sudo cp /usr/share/doc/bspwm/examples/bspwmrc $HOME/.config/bspwm/bspwmrc
        sudo cp /usr/share/doc/bspwm/examples/sxhkdrc $HOME/.config/sxhkd/sxhkdrc

        sudo chmod 755 $HOME/.config/bspwm/bspwmrc
        sudo chmod 755 $HOME/.config/sxhkd/sxhkdrc
    
    - name: Start xserver
      run: |
          # https://stackoverflow.com/questions/63125480/running-a-gui-application-on-a-ci-service-without-x11
          sudo xvfb-run -a --server-num=99 --auth-file=$HOME/.Xauthority bspwm &
          sleep 5
          sudo chmod 777 /tmp/*
          sleep 5
          sudo chmod 777 $HOME/.Xauthority
          # sleep 5
          # xhost si:localuser:root
          # export DISPLAY=:99
          # export XAUTHORITY=$HOME/.Xauthority
          # https://stackoverflow.com/questions/73490184/sudo-nautilus-gives-authorization-required-but-no-authorization-protocol-specif
          # xhost + 
        
          # export DISPLAY=:0
          # sudo Xvfb -ac :0 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          # sudo xvfb-run $HOME/.config/bspwm/bspwmrc &
          # $HOME/.config/bspwm/bspwmrc &

    # - name: Build and run container
    #   run: docker build . --file .github/workflows/Dockerfile --tag my-image-name:$(date +%s)
    #
    
    # - name: Generating Xauthority
    #   run: |
    #       touch $HOME/.Xauthority
    #       xauth generate :99 . trusted 
    #       xauth add ${HOST}:99 . $(xxd -l 16 -p /dev/urandom)
    #       xauth list 

    - name: Open window
      run: |
          export DISPLAY=:99
          zathura &
          # xauth list
          # ls -l /root
          # export DISPLAY=:99
          # xauth list
          # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

    - name: Test bspc
      run: ls -l /tmp/

    - name: Build
      run: cargo build --verbose

    - name: Build tests
      run: |
          cargo test --no-run --verbose

    - name: Run tests
      run: |
          export DISPLAY=:99
          cargo test --no-fail-fast --verbose -- --test-threads=1
